databases:
  - name: boca-chondor
    databaseName: boca_chondor_production
    user: scssquatch

services:
  - type: web
    name: boca-chondor
    env: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: boca_chondor_production
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
